### ISSUE TITLE
Improve HTML snapshot viewer

### ISSUE THREAD

**Issue by hubidu** [Codeception/codepress#4]
- The snapshot view should be scrollable
- The selector finder causes a high cpu load

**Comment by DavertMik** [comment]
Do we really need selector finder to work automatically all the time?
In most cases it is absolutely useless and it doesn't always provide good locators. I have some my own background with locator finders on page, I could put into the code. However, I would suggest to add a button "Locate" which will explicitly turn on locator mode.

As we have various types: CSS/XPath/Semantic locators - just showing CSS path is not the only way.

**Comment by hubidu** [comment]
Well, I find it very valuable and in most cases it produces decent selectors which will at least help you to get to a first version of your test quickly. Besides I also want to highlight the current element of the step. However a button to turn it on still makes sense.

Anyway the issue is more about improving the snapshot view in general.
