### ISSUE TITLE
Do not copy assets on start

### ISSUE THREAD

**Issue by DavertMik** [Codeception/codepress#8]
I see that copying extra stuff may lead to inconsistency between codepress and codeceptjs internally installed.

**Comment by hubidu** [comment]
I agree that's not very elegant, but what's the alternative? Besides codepress uses the installed codeceptjs version of the test project.

**Comment by DavertMik** [comment]
> Besides codepress uses the installed codeceptjs version of the test project.

No, we should change this because of compatibility issues. You don't want to answer something like why my CodeceptJS 2.0.4 is not working with codepress :smile: Me neither 

We should make codepress a standalone package, which will depend on codeceptjs version. We may also include codepress into codeceptjs package.json as well. So let's think that codepress and codeceptjs are sharing the same environment.
